sudo: required
language: node_js
node_js:
  - "6.0"
branches:
  only:
    - phase-1
env:
  global:
    - CXX=g++-4.8
  matrix:
    - GIT_VERSION=default
    - GIT_VERSION=edge
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - npm cache clean
  - if [ "$GIT_VERSION" = "edge" ]; then sudo add-apt-repository ppa:git-core/ppa -y && sudo apt-get update -q && sudo apt-get install -y git; fi
  - git config --global user.email "test@testy.com"
  - git config --global user.name "Test testy"
  - git version
install:
  - npm install

script:
  - npm run test-react