export const NO_OP = 'no-op';

export const FETCH_USER_CONFIG_REQUEST = 'FETCH_USER_CONFIG_REQUEST';
export const FETCH_LATEST_VERSION_REQUEST = 'FETCH_LATEST_VERSION_REQUEST';
export const FETCH_GIT_VERSION_REQUEST = 'FETCH_GIT_VERSION_REQUEST';
export const FETCH_UNGIT_CONFIG_REQUEST = 'FETCH_UNGIT_CONFIG_REQUEST';

export const FETCH_USER_CONFIG_FAILURE = 'FETCH_USER_CONFIG_FAILURE';
export const FETCH_LATEST_VERSION_FAILURE = 'FETCH_LATEST_VERSION_FAILURE';
export const FETCH_GIT_VERSION_FAILURE = 'FETCH_GIT_VERSION_FAILURE';
export const FETCH_UNGIT_CONFIG_FAILURE = 'FETCH_UNGIT_CONFIG_FAILURE';

export const FETCH_USER_CONFIG_SUCCESS = 'FETCH_USER_CONFIG_SUCCESS';
export const FETCH_LATEST_VERSION_SUCCESS = 'FETCH_LATEST_VERSION_SUCCESS';
export const FETCH_GIT_VERSION_SUCCESS = 'FETCH_GIT_VERSION_SUCCESS';
export const FETCH_UNGIT_CONFIG_SUCCESS = 'FETCH_UNGIT_CONFIG_SUCCESS';

export const DISMISS_GIT_VERSION_ERROR = 'DISMISS_GIT_VERSION_ERROR';