export const RECEIVE_GIT_VERSION = 'RECEIVE_GIT_VERSION';
export const RECEIVE_LATEST_VERSION = 'RECEIVE_LATEST_VERSION';
export const RECEIVE_USER_CONFIG = 'RECEIVE_USER_CONFIG';
export const RECEIVE_UNGIT_CONFIG = 'RECEIVE_UNGIT_CONFIG';
export const PATH_PAGE_PENDING = 'PATH_PAGE_PENDING';
export const PATH_PAGE_API_ERR = 'PATH_PAGE_API_ERR';